import concluintesGeneroCurso from './csv/concluintesPorGeneroECursoSBC.csv'
import concluintesGenero from './csv/concluintesPorGeneroSBC.csv'
import matriculadosGenero from './csv/matriculadosPorGenerpSBC.csv'
import matriculadosGeneroCurso from './csv/matriculadosPorGeneroECursoSBC.csv'
import cursosCriados from './csv/cursosCriadosSBC.csv'
import pesquisa from './csv/Pesquisa.csv'
import * as d3 from 'd3';

export async function carregarDados(){
    let data = [];

    // let aux = [];
    // await d3.csv(matriculadosGeneroCurso, function(d){
    //     aux.push(d)
    // });

    //console.log(aux);

    // let aux2 = [];
    // await d3.csv(concluintesGeneroCurso, function(e){
    //     aux2.push(e);
    // });

    let aux3 = [
        "identifico",
"tanto",
"difícil",
"poucas",
"pessoas",
"estão",
"dia",
"postas",
"ajudar",
"professor",
"complica",
"falta",
"reconhecimento",
"mostrar",
"resultados",
"possibilidades",
"bem",
"tentadoras",
"outras",
"áreas",
"Sintia-me",
"deslocada",
"curso",
"desafio",
"crescer",
"área",
"mulher",
"difícil",
"poucas",
"pessoas",
"estão",
"dia",
"postas",
"ajudar",
"professor",
"complica",
"Estou",
"campo",
"pesquisa",
"demora",
"conseguir",
"bolsa",
"desmotivante",
"conta",
"machismo",
"Sentimento",
"incapacidade",
"pela",
"discriminação",
"desigualdade",
"entre",
"homem",
"mulher",
"achei",
"fosse",
"já",
"meus",
"amigos",
"sabiam",
"tanto",
"eu",
"nem",
"tanto",
"assim",
"motivos",
"minha",
"ansiedade",
"depressão",
"falta",
"investimento",
"emprego",
"tive",
"pensei",
"parar",
"novos",
"desafios",
"horizontes",
"ajudar",
"outros",
"Machismo",
"validação",
"palavra",
"dificuldade",
"vários",
"momentos",
"senti",
"identificava",
"com",
"área",
"começo",
"minha",
"carreira",
"cara",
"tinha",
"ajudar",
"tinha",
"paciência",
"era",
"grosso",
"gostava",
"disso",
"Pensei",
"era",
"minha",
"área",
"encontrei",
"empresa",
"abraçou",
"consegui",
"desenvolver",
"naturalmente",
"começo",
"devido",
"as",
"dificuldades",
"temia",
"pudesse",
"ser",
"impedimento",
"durante",
"tempo",
"Existe",
"preconceito",
"área",
"muitos",
"ambientes",
"ainda",
"são",
"machistas",
"Consigo",
"trabalhar",
"freelancer",
"consigo",
"trabalho",
"CLT",
"causa",
"lista",
"enorme",
"exigências",
"das",
"empresas",
"há",
"grande",
"clima",
"competição",
"nessa",
"competição",
"as",
"mulheres",
"sempre",
"precisam",
"se",
"esforçar",
"acaba",
"sendo",
"exaustivo",
"Síndrome",
"impostor",
"achar",
"eu",
"quero",
"seguir",
"Desanimo",
"Machismo",
"Double",
"standards",
"cobrança",
"necessariamente",
"abandonar",
"pós",
"formada",
"conseguia",
"encontrar",
"carreira",
"desenvolvedora",
"via",
"assim",
"ao",
"meu",
"ver",
"meus",
"colegas",
"sempre",
"estavam",
"frente",
"Porém",
"hoje",
"gosto",
"área",
"sei",
"ela",
"oferece",
"inúmeras",
"oportunidades",
"Até",
"desejo",
"voltar",
"estudar",
"programação",
"só",
"seria",
"algo",
"pessoal",
"conta",
"discriminação",
"algo",
"tipo",
"Ritmo",
"acelerado",
"trabalho",
"Às",
"vezes",
"porque",
"identifico",
"completamente",
"com",
"perfil",
"pessoal",
"área",
"torna",
"trabalhar",
"nessa",
"área",
"desinteressante",
"às",
"vezes",
"Entrei",
"recentemente",
"Então",
"enquanto",
"null",
"fazer",
"algo",
"artística",
"dependo",
"posso",
"isolar",
"pouco",
"das",
"dinâmicas",
"gênero",
"síndrome",
"impostor",
"Eu",
"tenho",
"primeira",
"formação",
"Estou",
"tentando",
"estágio",
"nada",
"estou",
"desanimando",
"com",
"medo",
"Às",
"vezes",
"penso",
"voltar",
"antiga",
"carreira",
"além",
"TI",
"tenho",
"outros",
"interessses",
"gostaria",
"tentar",
"Abuso",
"sexual",
"abuso",
"psicológico",
"Falta",
"oportunidade",
"conhecimento",
"prático",
"Jr",
"Desistir",
"eu",
"cheguei",
"pensar",
"tenho",
"medo",
"conseguir",
"bom",
"emprego",
"sentir",
"ambientalizada",
"Já",
"abandonei",
"já",
"voltei",
"identifiquei",
"incialmente",
"machismo",
"preconceito",
"ter",
"mostrar",
"colegas",
"sexo",
"oposto",
"falta",
"oportunidade",
"Falta",
"representação",
"gera",
"insegurança",
"tempo",
"atrás",
"fui",
"engenharia",
"Acabei",
"voltando",
"computação",
"jeito",
"bom",
"Mercado",
"predominante",
"masculino",
"meu",
"estado",
"muita",
"pressão",
"difícil",
"porque",
"eu",
"queria",
"ser",
"tratada",
"sou",
"faculdade",
"pelo",
"resto",
"vida",
"achar",
"vou",
"dar",
"conta",
"dessa",
"área",
"saude",
"mental",
"Difícil",
"exigente",
"Curso",
"homens",
"falta",
"incentivo",
"ouvir",
"pessoas",
"falarem",
"eu",
"ser",
"mulher",
"cansativo",
"pressão",
"Nunca",
"Já",
"abandonei",
"muitas",
"ilegalidades",
"trabalhistas",
"machismo",
    ];

    aux3.forEach(e => {
        let palavra = e.toUpperCase();
        data.push(palavra)
    })
    //console.log(data)
    //data = aux3;

    let id = 0;

    // aux.forEach(a1 => {
    //     aux2.forEach(a2 => {
    //         if(a1.curso === a2.curso){
    //             if(a1.ano === a2.ano){
    //                 data.push({
    //                     id: id,
    //                     ano: +a1.ano,
    //                     curso: a1.curso,
    //                     nome: a1.curso + " " + a1.ano + " mulheres",
    //                     mat: +a1.fem,
    //                     conc: +a2.fem,
    //                     porc: (+a2.fem)*100 / (+a1.fem),   
    //                 })
    //                 id = id + 1;
    //                 data.push({
    //                     id: id,
    //                     ano: +a1.ano,
    //                     curso: a1.curso,
    //                     nome: a1.curso + " " + a1.ano + " homens",
    //                     mat: +a1.mas,
    //                     conc: +a2.mas,
    //                     porc: (+a2.mas)*100 / (+a1.mas),
    //                 })
    //                 id= id+ 1;
    //             }
    //         }
    //     })
    // })

    // aux.forEach(a1 => {
    //     aux2.forEach(a2 => {
    //         if(a1.ano === a2.ano){
    //             data.push({
    //                 "name": +a1.ano,
    //                 "children": [{
    //                     "name": "matriculados",
    //                     "value": (+a2.fem)+ (+a1.mas),
    //                     "children": [{
    //                         "name": "concluintes",
    //                         "children": [
    //                             {"name": "Mulheres", "value": +a1.fem},
    //                             {"name": "Homens", "value": a1.mas},
    //                         ]
    //                     }]
    //                 }],
    //             })
    //         }
    //     })
    // })

    // aux.forEach(a1 => {
    //     aux2.forEach(a2 => {
    //         //console.log(a1.Curso + " e " + a2.curso)
    //         if(a1.Curso === a2.curso){
    //             if(a1.ano === a2.ano){
    //                 data.push({
    //                     id: id,
    //                     ano: +a1.ano,
    //                     curso: a2.curso,
    //                     mulheres: +a1.fem,
    //                     homens: +a1.mas,
    //                     criados: +a2.num
    //                 });
    //                 id = id+1;
    //             }
    //         }
    //     });
    // });

    //console.log(data);
    return data;
}